controller:
  replicaCount: 2
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  service:
    type: LoadBalancer
  nodeSelector:
    "kubernetes.io/os": linux
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  admissionWebhooks:
    enabled: true
