apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      automountServiceAccountToken: true
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.14.1
          args:
            - --provider=aws
            - --domain-filter=ptm-app.com  
            - --policy=sync
            - --registry=txt
            - --txt-owner-id=external-dns
            - --source=service
            - --source=ingress
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: route53-credentials-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: route53-credentials-secret
                  key: secret-access-key
