name: Terraform & Security Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'


jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
    
      - name: Terraform Format
        run: terraform fmt -check    

      - name: Terraform Init
        run: terraform init ./terraform

      - name: Terraform Validate
        run: terraform validate ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan ./terraform

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

